caught ExA: ExA
caught re 2: java.lang.RuntimeException
Done!
